### ISSUE TITLE
Add user documentation section to banchan app

### ISSUE THREAD

**Issue by skullbunnygalaxy** [BanchanArt/banchan#137]
At some point, we need to have a section on banchan.art website that is user documentation including:
- what is banchan app?
- how to use banchan app (to commission or as an artist)?

**Comment by zkat** [comment]
We should probably have a CMS set up for this. After looking through a bunch of them, Netlify CMS seems pretty good, but I think we should do another survey and see if there's anything better. It might even make sense to just... use Wordpress.com and be done with it. Whatever we choose, it should definitely be minimal work for us.

Another alternative is to just write a basic CMS ourselves, which is not my preference because that's a lot of work to do right (I think?), but maybe that's worth exploring, too. We have a lot of the pieces available already, and it would allow us to more tightly integrate everything, like users, permissions, etc.

**Comment by skullbunnygalaxy** [comment]
Update: after a discussion on Discord, we have decided to pass on Netlify CMS due to it not having a robust built-in user management system. Currently looking into using Hugo or 11ty. 

I would love to write our own CMS. However, using a static site generator will definitely get this done quicker since the system is already in place.

**Comment by skullbunnygalaxy** [comment]
I compared Hugo to 11ty, specifically the features we want for documentation.

- Search feature: Hugo has more options, including Fusejs, which is super fast and already has multiple implementations developed for Hugo
- Github Pages Hosting: installing Hugo on GH Pages is straight forward whereas for 11ty you have to manually adjust every link due to the link format differing between GH Pages and 11ty. Hugo lets you adjust the link format in the config with a single line.
-  Existing documentation implementations: Hugo has 22 themes, aka starters, built explicitly for documentation. 11ty has one and a half. The starters are useful for reference to see how others implemented various features relevant to documentation sites. 
- Frontend: Hugo has a desktop GUI that users can install if they prefer not to write in markdown, but editing via Github seems to be the most user-friendly option right now even though it means writing in markdown. Both Hugo and 11ty recommend Netlify CMS for an online GUI, but Netlify CMS does not have the sort of built-in user management system that we are looking for. Rather than building our own CMS as suggested above, a possible alternative would be to build a front-end interface that hooks into existing user management systems, ie with Banchan's user system, for Hugo.

Next steps:
Setup a basic Hugo theme with tailwindcss 3 + daisyui + fusejs search to see how straightforward it is to implement these items within Hugo.

**Comment by zkat** [comment]
We have help.banchan.art and we'll be filling its knowledge base over time. Maybe we'll have an actual docs site at some point, but I don't think it's needed right now.
