### ISSUE TITLE
My Commissions: differentiating between commissioner and commissionee - UX issue

### ISSUE THREAD

**Issue by kjrsten** [BanchanArt/banchan#513]
When I look at "My Commissions" I see both things that i have commissioned others to do, and things that I owe other people, in the same list. I think these should be obvious as to what they are, and separated in some way.
<img width="1336" alt="Screen Shot 2023-07-14 at 7 21 27 PM" src="https://github.com/BanchanArt/banchan/assets/5471856/9e147ef0-322f-4331-8ffd-b1c6d06e2e26">

**Comment by kjrsten** [comment]
Here's my idea for differentiating these lists...

![banchan3](https://github.com/BanchanArt/banchan/assets/5471856/2d71b22f-1914-47df-8e4e-01034869658e)

**Comment by skullbunnygalaxy** [comment]
@rjt-rockx is currently redesigning the navigation in order to separate out the studio dashboard + management from the rest of the site, which should help clear this up. 

I'll let her go into more details, but here is a screenshot of her wip:


![Image](https://github.com/BanchanArt/banchan/assets/411004/9b7eb6c1-b46a-4fb2-a09b-33dc984e3045)
