### ISSUE TITLE
I was allowed to Request my own Offering + weird pricing/tip issue

### ISSUE THREAD

**Issue by kjrsten** [BanchanArt/banchan#519]
I was able to click the green "Request" button and request my own item (One Crow Outline) and make the request for my own commission Offering

Also, the Terms field was blank (reported in previous ticket, the Offering was created without Terms) but I still had to click to agree to terms.
<img width="915" alt="Screen Shot 2023-07-15 at 3 39 34 PM" src="https://github.com/BanchanArt/banchan/assets/5471856/8f777051-7e30-4e80-bb0e-0f86cccdab3f">

**Comment by kjrsten** [comment]
I was able to go through the entire process including deposit, invoicing, payment and pay out successfully; I received notifications and receipt emails.

The numbers look a bit odd to me, I don't see where I tipped... (the item price is $40)

I made a Deposit for $20

Then paid $20 for the balance, adding a $6 tip -- seems to me this should total $46

I received a Payout for $28.03

<img width="403" alt="Screen Shot 2023-07-15 at 3 47 58 PM" src="https://github.com/BanchanArt/banchan/assets/5471856/4e1e0bde-715d-4278-a518-2075fe3c882f">

<img width="1235" alt="Screen Shot 2023-07-15 at 3 49 44 PM" src="https://github.com/BanchanArt/banchan/assets/5471856/b53022a5-444e-4f88-a153-9a98cbccc319">

**Comment by kjrsten** [comment]
Here's where you can see evidence of my intended tip

<img width="831" alt="Screen Shot 2023-07-15 at 3 52 52 PM" src="https://github.com/BanchanArt/banchan/assets/5471856/bee467b5-0af1-4a0f-aebb-1b46c8a8a4d2">

**Comment by zkat** [comment]
So there's a couple of issues here:

1. Yes, you can commission your own studio. That's by design, as it wouldn't be out of the question when you have multiple owners of a studio
2. I talked about not requiring terms acceptance when there's no terms in the other issue
3. I'll look into these weird numbers and try to make them more intuitive

**Comment by kjrsten** [comment]
I was thinking about scenarios and yeah, I can see why you might commission your own studio!

**Comment by zkat** [comment]
oh ahahahaha @kjrsten the reason for your weird numbers is that you set up the commission to use AUD$ instead of USD$, but we transfer USD$ to you, and I guess my currency formatter isn't differentiating between the two:


![Image](https://github.com/BanchanArt/banchan/assets/17535/9f9a2898-0e5b-46cb-8f02-d936a5772642)
